const rentalInfoSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "RentalListing",
  type: "object",
  properties: {
    room_type: {
      type: "string",
      enum: ["雅房", "套房", "分租套房", "獨立套房"],
      description:
        "房型類型：雅房（無廁所與衛浴）、套房（有浴室但不確定是否獨立）、分租套房（共用空間）、獨立套房（無共用空間）",
    },
    monthly_rent: {
      type: "integer",
      minimum: 0,
      description: "每月租金，以新台幣計價。不含水電、管理費等其他費用。",
    },
    city: {
      type: "string",
      enum: ["台北市", "新北市"],
      description: "房源所在縣市名稱（行政區層級），目前支援台北市與新北市",
    },
    district: {
      type: "string",
      enum: [
        "中正",
        "大同",
        "中山",
        "松山",
        "大安",
        "萬華",
        "信義",
        "士林",
        "北投",
        "內湖",
        "南港",
        "文山",
        "板橋",
        "新莊",
        "中和",
        "永和",
        "土城",
        "蘆洲",
        "三重",
        "新店",
        "汐止",
        "樹林",
        "三峽",
        "鶯歌",
        "林口",
        "五股",
        "泰山",
        "八里",
        "深坑",
        "石碇",
        "坪林",
        "三芝",
        "石門",
        "金山",
        "萬里",
        "瑞芳",
        "平溪",
        "雙溪",
        "貢寮",
        "烏來",
      ],
      description: "房源所在行政區名稱，例如：大安、板橋等，需與 city 對應",
    },
    nearby_mrt_stations: {
      type: "array",
      items: {
        type: "string",
        enum: [
          "南港展覽館",
          "南港軟體園區",
          "東湖",
          "葫洲",
          "大湖公園",
          "內湖",
          "文德",
          "港墘",
          "西湖",
          "劍南路",
          "大直",
          "動物園",
          "木柵",
          "萬芳社區",
          "萬芳醫院",
          "辛亥",
          "麟光",
          "六張犁",
          "科技大樓",
          "大安",
          "忠孝復興",
          "南京復興",
          "中山國中",
          "松山機場",
          "松山",
          "南京三民",
          "台北小巨蛋",
          "南京復興",
          "松江南京",
          "中山",
          "北門",
          "西門",
          "小南門",
          "古亭",
          "台電大樓",
          "公館",
          "萬隆",
          "景美",
          "大坪林",
          "七張",
          "小碧潭",
          "新店區公所",
          "新店",
          "南勢角",
          "景安",
          "永安市場",
          "頂溪",
          "忠孝新生",
          "行天宮",
          "中山國小",
          "大橋頭",
          "台北橋",
          "菜寮",
          "三重",
          "先嗇宮",
          "頭前庄",
          "新莊",
          "輔大",
          "丹鳳",
          "迴龍",
          "頂埔",
          "永寧",
          "土城",
          "海山",
          "亞東醫院",
          "府中",
          "板橋",
          "新埔",
          "江子翠",
          "龍山寺",
          "善導寺",
          "忠孝敦化",
          "國父紀念館",
          "市政府",
          "永春",
          "後山埤",
          "昆陽",
          "南港",
        ],
      },
      description:
        "附近捷運站名稱，可包含一個或多個捷運站，例如：忠孝復興、中山",
    },
    floor_number: {
      type: "integer",
      minimum: 0,
      description: "所在樓層（若為地下層請用 0 表示）",
    },
    electricity_fee_type: {
      type: "string",
      enum: ["台電計價", "房東計價", "其他"],
      description: "電費計價方式，例如依照台電計價、或由房東自行訂價",
    },
    electricity_rate: {
      type: "number",
      description: "電費計價方式為房東計價時，此欄位為每度電的費用（新台幣元）",
    },
    management_fee: {
      type: "integer",
      minimum: 0,
      description: "每月管理費，若無則填 0",
    },
    total_floors: {
      type: "integer",
      minimum: 1,
      description: "總樓層數，例如：整棟為 5 層樓，填 5",
    },
    is_top_floor_addition: {
      type: "boolean",
      description: "是否為頂樓加蓋，true 表示是",
    },
  },
  required: ["roomType", "monthlyRent", "city", "district"],
};

export { rentalInfoSchema };
